apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhpam-secret
  namespace: {{ .Values.global.rhpam.namespace }}
  labels: {{- include "commonLabels" . | indent 4 }}
stringData:
  MAVEN_REPO_USERNAME: {{ .Values.maven.repo.username }}
  MAVEN_REPO_PASSWORD: {{ .Values.maven.repo.password }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhpam-git-hooks-secret
  namespace: {{ .Values.global.rhpam.namespace }}
  labels: {{- include "commonLabels" . | indent 4 }}
stringData:
  id_rsa: |
{{ .Files.Get "resources/git/id_rsa" | indent 4 }}
  known_hosts: |
{{ .Files.Get "resources/git/known_hosts" | indent 4 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhpam-custom-secret
  namespace: {{ .Values.global.rhpam.namespace }}
  labels: {{- include "commonLabels" . | indent 4 }}
stringData:
{{- range $k, $v := .Values.customSecrets }}
  {{- $variableName := include "envVariableName" $k }}
  {{- printf "\n%s: %s" $variableName ($v | quote) | indent 2 }}
{{- end }}
