apiVersion: v2
name: rhpam
description: A Helm chart to install RHPAM on Openshift using the RHPAM operator

type: application
version: 0.1.0
# This is NOT used as the tag for RHPAM images, matches common.version property
appVersion: 7.9.1
